/* ─────────────────────────────────────────────────────────────────────────
   Google Fonts catalog + loaders for the Fonts tool.

   The full catalog ships as a bundled JSON (src/data/google-fonts.json,
   generated by scripts/generate-google-fonts.mjs) so no API key is needed.
   It is imported lazily (`?raw` → its own Vite chunk) the first time the
   picker opens. Two loaders inject css2 <link> stylesheets:

   - loadPreviewFont: a tiny `text=`-subset request (the family name's own
     letters, weight 400) so picker rows can render in their typeface.
   - loadGoogleFont: the real thing — every weight/italic the family actually
     has (per the bundled metadata; css2 rejects axis values a family lacks),
     so existing bold/italic page text keeps real faces after a swap.
───────────────────────────────────────────────────────────────────────── */

export interface GoogleFont {
  family: string
  category: string // sans-serif | serif | display | handwriting | monospace
  weights: number[] // upright weights actually available, ascending
  italic: boolean
}

interface CatalogJson {
  categories: string[]
  families: [string, number, number[], 0 | 1][]
}

let listPromise: Promise<GoogleFont[]> | null = null

/** The full Google Fonts catalog, decoded from the bundled JSON (memoized). */
export function loadGoogleFontsList(): Promise<GoogleFont[]> {
  if (!listPromise) {
    listPromise = import('@/data/google-fonts.json?raw').then((mod) => {
      const data = JSON.parse(mod.default) as CatalogJson
      return data.families.map(([family, cat, weights, italic]) => ({
        family,
        category: data.categories[cat] ?? 'display',
        weights,
        italic: italic === 1,
      }))
    })
    // Let a transient failure (offline dev) retry on the next open.
    listPromise.catch(() => {
      listPromise = null
    })
  }
  return listPromise
}

function appendStylesheet(href: string, attr: string): HTMLLinkElement {
  const link = document.createElement('link')
  link.rel = 'stylesheet'
  link.href = href
  link.setAttribute(attr, '')
  document.head.appendChild(link)
  return link
}

const familyParam = (family: string): string => family.trim().replace(/ /g, '+')

// ── Preview loading (picker rows) ───────────────────────────────────────────

const previewLoaded = new Set<string>()

/* Load just enough of `family` to draw its own name: weight 400, subset to the
   name's letters via `text=` (~1–2 KB). Fire-and-forget; deduped per family. */
export function loadPreviewFont(family: string): void {
  if (previewLoaded.has(family)) return
  previewLoaded.add(family)
  appendStylesheet(
    `https://fonts.googleapis.com/css2?family=${familyParam(family)}&text=${encodeURIComponent(family)}&display=swap`,
    'data-gf-preview',
  )
}

// ── Full loading (applying a replacement) ────────────────────────────────────

const fullLoads = new Map<string, Promise<void>>()

/* css2 axis-tuple list for everything the family ships. Tuples must be sorted
   ascending with all upright (0,w) before italic (1,w); families without
   italics use the plain `wght@…` form (an unused `ital` axis is an error). */
function css2AxisList(font: GoogleFont): string {
  if (!font.italic) return `wght@${font.weights.join(';')}`
  const tuples = [
    ...font.weights.map((w) => `0,${w}`),
    ...font.weights.map((w) => `1,${w}`),
  ]
  return `ital,wght@${tuples.join(';')}`
}

/* Load the family for real. Resolves once the stylesheet + a representative
   face are in (or after a 3s cap, so a slow network never wedges the caller —
   display=swap paints the font whenever it does land). Deduped per family. */
export function loadGoogleFont(font: GoogleFont): Promise<void> {
  let p = fullLoads.get(font.family)
  if (p) return p

  const href = `https://fonts.googleapis.com/css2?family=${familyParam(font.family)}:${css2AxisList(font)}&display=swap`
  const loaded = new Promise<void>((resolve) => {
    const link = appendStylesheet(href, 'data-gf-full')
    link.onload = () => {
      const probe = `${font.weights.includes(400) ? 400 : font.weights[0]} 16px "${font.family}"`
      document.fonts.load(probe).then(
        () => resolve(),
        () => resolve(),
      )
    }
    link.onerror = () => resolve() // apply proceeds; text keeps its fallback
  })
  const timeout = new Promise<void>((resolve) => {
    window.setTimeout(resolve, 3000)
  })
  p = Promise.race([loaded, timeout])
  fullLoads.set(font.family, p)
  return p
}

/** CSS generic to fall back on when an original stack has no tail to keep. */
export function genericFallbackFor(category: string): string {
  switch (category) {
    case 'serif':
      return 'serif'
    case 'monospace':
      return 'monospace'
    case 'handwriting':
      return 'cursive'
    default: // sans-serif, display
      return 'sans-serif'
  }
}
