/* ─────────────────────────────────────────────────────────────────────────
   session-create — mints a share-link session with a plan-based lifetime.

   Why this exists: a session row's `expires_at` used to be chosen by the browser
   and inserted with the anon key (sessions RLS is intentionally open), so a Free
   user could hand themselves a never-expiring link from devtools. Lifetime is now
   resolved from the caller's server-verified Clerk identity → live Kelviq plan:
   Free 24h / Pro 30d / Max never (see SHARE_EXPIRY_MS).

   IMPORTANT — this function is an ELEVATOR, not a gate. The security boundary is
   the `enforce_session_expiry` trigger in schema.sql, which caps every anon insert
   at the Free duration and pins `expires_at` on UPDATE. That's what lets the client
   fall back to a direct insert when it can't reach this function (signed out, no
   token on Firefox, cold start): the fallback simply lands at Free's 24h. So a
   failure here degrades the DURATION, never the ability to share.

   The session id is generated by the CLIENT and posted here (matching the existing
   convention for both tables — see schema.sql). That keeps a retry idempotent: if
   the response is lost after the row commits, retrying with the same id hits the
   primary key and we treat 23505 as success instead of orphaning a row. It also
   lets the caller compute the share URL before awaiting us.

   We return the STORED row rather than the value we computed, so an unexpected
   silent clamp (a role outside the trigger's whitelist, a self-hosted setup) shows
   up as an observable mismatch instead of the dialog promising "never expires" for
   a link the DB kills in a day.

     POST { id, pageUrl, createdBy? } → { id, expiresAt, plan }

   `expiresAt` is an ISO string, or null for "never expires" (Max).

   Auth: the caller's Clerk session token (x-clerk-token), verified server-side.
   Trusted-backend pattern, identical to annotation-quota and the kelviq-*
   functions: verify_jwt = false (so the gateway doesn't 401 the CORS preflight) +
   authenticateUser(req) + service-role DB access (bypasses RLS and satisfies the
   trigger's trusted-role check).

   Deno (Supabase Edge Function) — never goes through the app's `tsc -b`.
───────────────────────────────────────────────────────────────────────── */

import { handlePreflight, json } from '../_shared/cors.ts'
import { authenticateUser } from '../_shared/clerk.ts'
import { db, livePlanForCustomer } from '../_shared/kelviq.ts'
import { SHARE_EXPIRY_MS } from '../_shared/plans.ts'

const SESSIONS_TABLE = 'sessions'

/** The column is `uuid`, so a non-uuid id would fail the insert anyway — reject
    it here with an actionable message rather than a Postgres type error. */
const UUID_RE =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i

/** Bound on page_url so a malformed caller can't write an unbounded row. */
const MAX_URL_LEN = 2048
const MAX_NAME_LEN = 200

/** Postgres unique-violation — the row already exists, so a retry succeeded. */
const PG_UNIQUE_VIOLATION = '23505'

Deno.serve(async (req) => {
  const preflight = handlePreflight(req)
  if (preflight) return preflight
  if (req.method !== 'POST') return json({ error: 'Method not allowed' }, 405)

  const auth = await authenticateUser(req)
  if (!auth.ok) {
    console.error('[session-create] auth failed:', auth.reason)
    return json({ error: 'Unauthorized', reason: auth.reason }, 401)
  }
  const userId = auth.user.userId

  let payload: { id?: unknown; pageUrl?: unknown; createdBy?: unknown }
  try {
    payload = await req.json()
  } catch {
    return json({ error: 'Invalid JSON body' }, 400)
  }

  const id = typeof payload.id === 'string' ? payload.id.trim() : ''
  if (!UUID_RE.test(id)) return json({ error: 'id must be a uuid' }, 400)

  const pageUrl =
    typeof payload.pageUrl === 'string' ? payload.pageUrl.trim() : ''
  if (!pageUrl) return json({ error: 'pageUrl is required' }, 400)
  if (pageUrl.length > MAX_URL_LEN) {
    return json({ error: 'pageUrl is too long' }, 400)
  }

  const createdBy =
    typeof payload.createdBy === 'string'
      ? payload.createdBy.trim().slice(0, MAX_NAME_LEN)
      : ''

  try {
    const live = await livePlanForCustomer(userId)
    const ttlMs = SHARE_EXPIRY_MS[live.plan] // number | null (null = never)
    const expiresAt =
      ttlMs === null ? null : new Date(Date.now() + ttlMs).toISOString()

    const { data, error } = await db()
      .from(SESSIONS_TABLE)
      .insert({
        id,
        page_url: pageUrl,
        active: true,
        created_by: createdBy,
        expires_at: expiresAt,
      })
      .select('id, expires_at')
      .single()

    if (error) {
      // Idempotent retry: the row landed on an earlier attempt whose response we
      // lost. Read it back so the caller still learns the real expiry.
      if (error.code === PG_UNIQUE_VIOLATION) {
        const existing = await db()
          .from(SESSIONS_TABLE)
          .select('id, expires_at')
          .eq('id', id)
          .maybeSingle()
        if (existing.data) {
          return json({
            id: existing.data.id,
            expiresAt: existing.data.expires_at ?? null,
            plan: live.plan,
          })
        }
      }
      throw new Error(error.message)
    }

    return json({
      id: data.id,
      // DB truth, not the value computed above — see the header note.
      expiresAt: data.expires_at ?? null,
      plan: live.plan,
    })
  } catch (err) {
    const message =
      err instanceof Error ? err.message : 'Session creation failed'
    console.error('[session-create] failed:', message)
    return json({ error: message }, 502)
  }
})
